-- Generated from data.xlsx, sheet data2, rows 2-18. No source values rewritten.
SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO categories (id, name, slug) VALUES (1, 'Bâtiment', 'batiment');
INSERT INTO categories (id, name, slug) VALUES (2, 'Services', 'services');
INSERT INTO categories (id, name, slug) VALUES (3, 'Fabrication', 'fabrication');
INSERT INTO categories (id, name, slug) VALUES (4, 'Alimentation', 'alimentation');
INSERT INTO specialties (id, name, category_id) VALUES (1, 'Boucher', 4);
INSERT INTO specialties (id, name, category_id) VALUES (2, 'Boulanger', 4);
INSERT INTO specialties (id, name, category_id) VALUES (3, 'Chocolatier', 4);
INSERT INTO specialties (id, name, category_id) VALUES (4, 'Traiteur', 4);
INSERT INTO specialties (id, name, category_id) VALUES (5, 'Chauffagiste', 1);
INSERT INTO specialties (id, name, category_id) VALUES (6, 'Electricien', 1);
INSERT INTO specialties (id, name, category_id) VALUES (7, 'Menuisier', 1);
INSERT INTO specialties (id, name, category_id) VALUES (8, 'Plombier', 1);
INSERT INTO specialties (id, name, category_id) VALUES (9, 'Bijoutier', 3);
INSERT INTO specialties (id, name, category_id) VALUES (10, 'Couturier', 3);
INSERT INTO specialties (id, name, category_id) VALUES (11, 'Ferronier', 3);
INSERT INTO specialties (id, name, category_id) VALUES (12, 'Coiffeur', 2);
INSERT INTO specialties (id, name, category_id) VALUES (13, 'Fleuriste', 2);
INSERT INTO specialties (id, name, category_id) VALUES (14, 'Toiletteur', 2);
INSERT INTO specialties (id, name, category_id) VALUES (15, 'Webdesign', 2);
INSERT INTO cities (id, name) VALUES (1, 'Lyon');
INSERT INTO cities (id, name) VALUES (2, 'Montélimar');
INSERT INTO cities (id, name) VALUES (3, 'Evian');
INSERT INTO cities (id, name) VALUES (4, 'Chamonix');
INSERT INTO cities (id, name) VALUES (5, 'Bourg-en-bresse');
INSERT INTO cities (id, name) VALUES (6, 'Vienne');
INSERT INTO cities (id, name) VALUES (7, 'Aix-les-bains');
INSERT INTO cities (id, name) VALUES (8, 'Annecy');
INSERT INTO cities (id, name) VALUES (9, 'Le Puy-en-Velay');
INSERT INTO cities (id, name) VALUES (10, 'Saint-Priest');
INSERT INTO cities (id, name) VALUES (11, 'Chambéry');
INSERT INTO cities (id, name) VALUES (12, 'Romans-sur-Isère');
INSERT INTO cities (id, name) VALUES (13, 'Annonay');
INSERT INTO cities (id, name) VALUES (14, 'Valence');
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (1, 'Boucherie Dumont', 4.5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'boucherie.dumond@gmail.com', NULL, 0, 1, 1);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (2, 'Au pain chaud', 4.8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'aupainchaud@hotmail.com', NULL, 1, 2, 2);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (3, 'Chocolaterie Labbé', 4.9, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'chocolaterie-labbe@gmail.com', 'https://chocolaterie-labbe.fr', 1, 3, 1);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (4, 'Traiteur Truchon', 4.1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'contact@truchon-traiteur.fr', 'https://truchon-traiteur.fr', 0, 4, 1);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (5, 'Orville Salmons', 5.0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'o-salmons@live.com', NULL, 1, 5, 3);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (6, 'Mont Blanc Eléctricité', 4.5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'contact@mont-blanc-electricite.com', 'https://mont-blanc-electricite.com', 0, 6, 4);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (7, 'Boutot & fils', 4.7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'boutot-menuiserie@gmail.com', 'https://boutot-menuiserie.com', 0, 7, 5);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (8, 'Vallis Bellemare', 4.0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'v.bellemare@gmail.com', 'https://plomberie-bellemare.com', 0, 8, 6);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (9, 'Claude Quinn', 4.2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'claude.quinn@gmail.com', NULL, 0, 9, 7);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (10, 'Amitee Lécuyer', 4.5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'a.amitee@hotmail.com', 'https://lecuyer-couture.com', 0, 10, 8);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (11, 'Ernest Carignan', 5.0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'e-carigan@hotmail.com', NULL, 0, 11, 9);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (12, 'Royden Charbonneau', 3.8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'r.charbonneau@gmail.com', NULL, 0, 12, 10);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (13, 'Leala Dennis', 3.8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'l.dennos@hotmail.fr', 'https://coiffure-leala-chambery.fr', 0, 12, 11);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (14, 'C''est sup''hair', 4.1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'sup-hair@gmail.com', 'https://sup-hair.fr', 0, 12, 12);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (15, 'Le monde des fleurs', 4.6, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'contact@le-monde-des-fleurs-annonay.fr', 'https://le-monde-des-fleurs-annonay.fr', 0, 13, 13);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (16, 'Valérie Laderoute', 4.5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'v-laredoute@gmail.com', NULL, 0, 14, 14);
INSERT INTO artisans (id, name, rating, about, email, website, is_top, specialty_id, city_id) VALUES (17, 'CM Graphisme', 4.4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin. ', 'contact@cm-graphisme.com', 'https://cm-graphisme.com', 0, 15, 14);
COMMIT;
